version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform_1.0.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - echo Initializing Terraform...
      - terraform init
      - echo Planning Terraform changes...
      - terraform plan -out=tfplan
  post_build:
    commands:
      - echo Applying Terraform changes...
      - terraform apply -auto-approve tfplan
artifacts:
  files:
    - '**/*'
  discard-paths: yes
